### ISSUE TITLE
data-analysis vignette

### ISSUE THREAD

**Issue by tbradley1013** [taywater/pwdgsi#5]
The `vignettes/data-analysis.Rmd` script is failing to build on the pwdrstudio server. The current reason for failure is [the database connection](https://github.com/taywater/pwdgsi/blob/master/vignettes/data-analysis.rmd#L41) . 

However, the reference to your `A:/` drive in your `directory` definition is also an issue. That drive is not mounted on the server. If you need to save intermediate plots, you should be saving them in the `inst/` folder of this directory and referencing them like that. 

The only place that the `directory` variable is used is in [this for loop](https://github.com/taywater/pwdgsi/blob/master/vignettes/data-analysis.rmd#L247-L275). It looks like that chunk is not even being evaluated on the run so the issue will likely lie in how you are calling these figures in [the subsequent figure calls](https://github.com/taywater/pwdgsi/blob/master/vignettes/data-analysis.rmd#L280-L292).

**Comment by tbradley1013** [comment]
Actually, I just looked at the figure calls, they should work since the figures are saved in the `vignettes` folder. and since the for loop isn't actually evaluated, that should be fine too...

so your only issue will probably be the database connection (assuming the rest of your code runs normally and isn't referencing any local files)

**Comment by taywater** [comment]
This was fixed a few version numbers ago.
